# Generated by Django 5.1.1 on 2024-09-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='other_free_text',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_option', models.TextField()),
                ('weight_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hri.question')),
            ],
        ),
    ]
