# Generated by Django 5.1.1 on 2024-10-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri', '0002_answer_other_group_score_question_other_free_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='survey',
        ),
        migrations.AlterField(
            model_name='survey',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hri.group'),
        ),
    ]
