# Generated by Django 5.1.1 on 2024-10-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri', '0004_remove_weight_weight_option_survey_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight_question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
