# Generated by Django 5.1.1 on 2024-10-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri', '0005_alter_weight_weight_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight_choice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
