# Generated by Django 5.1.1 on 2024-10-20 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri', '0006_question_weight_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='weight_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hri.weight'),
        ),
    ]
