# Generated by Django 5.1.1 on 2024-10-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri', '0007_alter_question_weight_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
