# Generated by Django 5.1.1 on 2024-10-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hri', '0008_question_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
    ]
