# Generated by Django 5.1.1 on 2024-11-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri', '0010_alter_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_0_points_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_0_points_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_0_points_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_0_points_sk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_1_points_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_1_points_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_1_points_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_1_points_sk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_2_points_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_2_points_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_2_points_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_2_points_sk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='weight_question_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='weight_question_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='weight_question_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='weight_question_sk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
