# Generated by Django 5.1.1 on 2024-11-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri', '0011_question_answer_0_points_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='body')),
                ('body_lt', models.TextField(null=True, verbose_name='body')),
                ('body_en', models.TextField(null=True, verbose_name='body')),
                ('body_pt', models.TextField(null=True, verbose_name='body')),
                ('body_sk', models.TextField(null=True, verbose_name='body')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_lt', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_pt', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_sk', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('notes', models.TextField(verbose_name='notes')),
                ('notes_lt', models.TextField(null=True, verbose_name='notes')),
                ('notes_en', models.TextField(null=True, verbose_name='notes')),
                ('notes_pt', models.TextField(null=True, verbose_name='notes')),
                ('notes_sk', models.TextField(null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
    ]
