# Generated by Django 5.1.1 on 2024-11-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri', '0012_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='text',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='text',
            name='notes_lt',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='text',
            name='notes_pt',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='text',
            name='notes_sk',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
